<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use common\models\PhoneValidator;

/**
 * This is the base-model class for table "apply_to_play".
 *
 * @property integer $apply_to_play_id
 * @property string $username
 * @property integer $phone_number
 * @property string $email
 * @property string $city
 * @property string $province
 * @property integer $auditor_id
 * @property string $region
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class ApplyToPlay extends \yii\db\ActiveRecord
{

     public $verifyCode;

     CONST  APPLY_TO_PLAY_STATUS_AUDIT = 1;//待审核
     CONST  APPLY_TO_PLAY_STATUS_SUCCEED = 2;//审核成功

     public static function OptsStatus(){
        return [
            self::APPLY_TO_PLAY_STATUS_AUDIT   =>'待审核',
            self::APPLY_TO_PLAY_STATUS_SUCCEED =>'审核成功'
            ];
     }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'apply_to_play';
    }

    public static function getDb(){
        return Yii::$app->get('campus');
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'phone_number', 'age'], 'required'],
            ['verifyCode','captcha','on'=>'AjaxApply'],
            [['verifyCode'],'required','on'=>'AjaxApply'],
            ['phone_number', 'string', 'min' => 11, 'max' => 11],
            [['phone_number'], PhoneValidator::className()],
            ['status','default','value'=>ApplyToPlay::APPLY_TO_PLAY_STATUS_AUDIT],
            // ['email','email'],
            [['auditor_id', 'status', 'province_id', 'school_id', 'age'], 'integer'],
            [['username'], 'string', 'max' => 255],
        ];
    }
    public  function scenarios(){
        $scenarios = parent::scenarios();
        //$scenarios['AjaxApply'] = ['verifyCode'];
        return $scenarios;
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'apply_to_play_id' => Yii::t('common', 'Apply To Play ID'),
            'username'         => Yii::t('common', '姓名'),
            'phone_number'     => Yii::t('common', '电话'),
            'age'              => Yii::t('common', '年龄'),
            'province_id'      => Yii::t('common', '地区'),
            'school_id'        => Yii::t('common', '校区'),
            // 'email'            => Yii::t('common', '邮件'),
            // 'city'             => Yii::t('common', '市'),
            // 'province'         => Yii::t('common', '省'),
            'auditor_id'       => Yii::t('common', '审核人'),
            // 'region'           => Yii::t('common', '区'),
            'verifyCode'       =>Yii::t('common','验证码'),
            'created_at'       => Yii::t('common', 'Created At'),
            'updated_at'       => Yii::t('common', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'username'     => Yii::t('common', '报名人姓名'),
            'phone_number' => Yii::t('common', '报名人电话'),
            'age'          => Yii::t('common', '年龄'),
            'province_id'  => Yii::t('common', '地区'),
            'school_id'    => Yii::t('common', '校区'),
            // 'email'        => Yii::t('common', '报名人邮件'),
            // 'city'         => Yii::t('common', '市'),
            // 'province'     => Yii::t('common', '省'),
            'auditor_id'   => Yii::t('common', '审核人'),
            // 'region'       => Yii::t('common', '区'),
            'status'       => Yii::t('common', '报名成功：1，报名审核： 2，已过期：3'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\ApplyToPlayQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \frontend\models\query\ApplyToPlayQuery(get_called_class());
    }


}
