<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "session".
 *
 * @property string $id
 * @property integer $expire
 * @property integer $user_id
 * @property string $udid
 * @property resource $data
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class Session extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'session';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['user_id'], 'integer'],
            [['data'], 'string'],
            [['id'], 'string', 'max' => 40],
            [['udid'], 'string', 'max' => 255],
            [['expire'], 'filter', 'filter' => 'strtotime', 'skipOnEmpty' => true],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('common', 'ID'),
            'expire' => Yii::t('common', '过期时间'),
            'user_id' => Yii::t('common', 'User ID'),
            'udid' => Yii::t('common', 'Udid'),
            'data' => Yii::t('common', 'Data'),
            'created_at' => Yii::t('common', 'Created At'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SessionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SessionQuery(get_called_class());
    }


}
