<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "activation_code".
 *
 * @property integer $activation_code_id
 * @property string $activation_code
 * @property integer $courseware_id
 * @property integer $course_order_item_id
 * @property integer $school_id
 * @property integer $grade_id
 * @property integer $user_id
 * @property integer $introducer_id
 * @property integer $payment
 * @property integer $status
 * @property string $total_price
 * @property string $real_price
 * @property string $coupon_price
 * @property integer $coupon_type
 * @property integer $expired_at
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class ActivationCode extends \yii\db\ActiveRecord
{


    public static function getDb(){
        //return \Yii::$app->modules['campus']->get('campus');
        return Yii::$app->get('campus');
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'activation_code';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['courseware_id', 'course_order_item_id', 'school_id', 'grade_id', 'user_id', 'introducer_id', 'payment', 'status', 'coupon_type', 'expired_at'], 'integer'],
            [['user_id', 'payment', 'total_price', 'real_price', 'expired_at'], 'required'],
            [['total_price', 'real_price', 'coupon_price'], 'number'],
            [['activation_code'], 'string', 'max' => 32]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'activation_code_id' => Yii::t('models', 'Activation Code ID'),
            'activation_code' => Yii::t('models', '激活码'),
            'courseware_id' => Yii::t('models', '课件id'),
            'course_order_item_id' => Yii::t('models', '订单ID'),
            'school_id' => Yii::t('models', 'School ID'),
            'grade_id' => Yii::t('models', 'Grade ID'),
            'user_id' => Yii::t('models', 'User ID'),
            'introducer_id' => Yii::t('models', '介绍人'),
            'payment' => Yii::t('models', '100 在线支付； 110 支付宝 支付 ； 111 微信支付；  200 货到付款'),
            'status' => Yii::t('models', '激活码状态：10未激活，20已经激活'),
            'total_price' => Yii::t('models', '总价'),
            'real_price' => Yii::t('models', '实际付款'),
            'coupon_price' => Yii::t('models', '优惠金额'),
            'coupon_type' => Yii::t('models', '优惠类型,2首单减免,3随机减免'),
            'expired_at' => Yii::t('models', '过期时间'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'activation_code' => Yii::t('models', '激活码'),
            'courseware_id' => Yii::t('models', '课件id'),
            'course_order_item_id' => Yii::t('models', '订单ID'),
            'introducer_id' => Yii::t('models', '介绍人'),
            'payment' => Yii::t('models', '100 在线支付； 110 支付宝 支付 ； 111 微信支付；  200 货到付款'),
            'status' => Yii::t('models', '激活码状态：10未激活，20已经激活'),
            'total_price' => Yii::t('models', '总价'),
            'real_price' => Yii::t('models', '实际付款'),
            'coupon_price' => Yii::t('models', '优惠金额'),
            'coupon_type' => Yii::t('models', '优惠类型,2首单减免,3随机减免'),
            'expired_at' => Yii::t('models', '过期时间'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\ActivationCodeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\ActivationCodeQuery(get_called_class());
    }


}
