<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;

/**
 * This is the base-model class for table "cn_city".
 *
 * @property integer $city_id
 * @property string $city_name
 * @property integer $province_id
 * @property string $first_letter
 * @property string $aliasModel
 */
abstract class CnCity extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cn_city';
    }

    public static function getDb(){
         //return \Yii::$app->modules['campus']->get('campus');
        return Yii::$app->get('campus');
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['city_id', 'city_name', 'province_id'], 'required'],
            [['city_id', 'province_id'], 'integer'],
            [['city_name'], 'string', 'max' => 50],
            [['first_letter'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'city_id' => Yii::t('common', 'City ID'),
            'city_name' => Yii::t('common', 'City Name'),
            'province_id' => Yii::t('common', 'Province ID'),
            'first_letter' => Yii::t('common', 'First Letter'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\CnCity the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\CnCity(get_called_class());
    }


}
