<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;

/**
 * This is the base-model class for table "collect".
 *
 * @property integer $collect_id
 * @property integer $user_id
 * @property integer $courseware_id
 * @property integer $play_back_time
 * @property integer $page_view
 * @property integer $type
 * @property integer $status
 * @property string $aliasModel
 */
abstract class Collect extends \yii\db\ActiveRecord
{

    CONST STATUS_COLLECTED  = 10; // 已收藏
    CONST STATUS_NOTCOLLECT = 20; // 取消收藏

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'collect';
    }

    /**
     * @inheritdoc
     */
    public static function getDb(){
       return \Yii::$app->get('campus');
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['courseware_master_id', 'status'], 'required'],
            [['collect_id', 'user_id', 'courseware_master_id', 'courseware_id', 'play_back_time', 'page_view','status'], 'integer'],
            [['type'],'string','max' => 128],
            ['user_id', 'default', 'value' => Yii::$app->user->identity->id],
            ['page_view', 'default', 'value' => 0],
            ['type', 'default', 'value' => ''],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'collect_id' => 'Collect ID',
            'user_id' => 'User ID',
            'courseware_master_id' => 'Courseware Master ID',
            'courseware_id' => 'Courseware ID',
            'play_back_time' => 'Play Back Time',
            'page_view' => 'Page View',
            'type' => 'Type',
            'status' => 'Status',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'user_id' => '用户id',
            'play_back_time' => '播放的时间断点',
            'page_view' => '浏览次数',
            'type' => '文件类型',
            'status' => '10 收藏；20取消收藏',
        ]);
    }




}
