<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "courseware_to_file".
 *
 * @property integer $courseware_to_file_id
 * @property integer $school_id
 * @property integer $grade_id
 * @property string $title
 * @property integer $status
 * @property integer $sort
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class CoursewareToFile extends \yii\db\ActiveRecord
{


     /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'courseware_to_file';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['school_id', 'grade_id', 'title'], 'required'],
            [['school_id', 'grade_id', 'status', 'sort'], 'integer'],
            [['title'], 'string', 'max' => 512]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'courseware_to_file_id' => Yii::t('common', '课件附件关系自增ID'),
            'school_id' => Yii::t('common', '学校ID'),
            'grade_id' => Yii::t('common', '班级ID'),
            'title' => Yii::t('common', '标题'),
            'status' => Yii::t('common', '1：正常；0标记删除；2待审核； '),
            'sort' => Yii::t('common', '默认与排序'),
            'updated_at' => Yii::t('common', 'Updated At'),
            'created_at' => Yii::t('common', 'Created At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'courseware_to_file_id' => Yii::t('common', '课件附件关系自增ID'),
            'school_id' => Yii::t('common', '学校ID'),
            'grade_id' => Yii::t('common', '班级ID'),
            'title' => Yii::t('common', '标题'),
            'status' => Yii::t('common', '1：正常；0标记删除；2待审核； '),
            'sort' => Yii::t('common', '默认与排序'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\CoursewareToFileQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\CoursewareToFileQuery(get_called_class());
    }


}
