<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "course".
 *
 * @property integer $course_id
 * @property integer $school_id
 * @property integer $grade_id
 * @property string $title
 * @property string $intro
 * @property integer $courseware_id
 * @property integer $creater_id
 * @property integer $start_time
 * @property integer $end_time
 * @property integer $status
 * @property integer $updeated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class Course extends \yii\db\ActiveRecord
{

    CONST COURSE_STATUS_OPEN = 10;//正常

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course';
    }
    public static function getDb(){
       return \Yii::$app->modules['campus']->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['school_id', 'grade_id', 'title', 'intro', 'courseware_id', 'creater_id', 'start_time', 'end_time', 'status', 'updeated_at'], 'required'],
            [['school_id', 'grade_id', 'courseware_id', 'creater_id', 'start_time', 'end_time', 'status', 'updeated_at'], 'integer'],
            [['title'], 'string', 'max' => 11],
            [['intro'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'course_id' => Yii::t('common', 'Course ID'),
            'school_id' => Yii::t('common', 'School ID'),
            'grade_id' => Yii::t('common', 'Grade ID'),
            'title' => Yii::t('common', '课程名称'),
            'intro' => Yii::t('common', '课程介绍'),
            'courseware_id' => Yii::t('common', '课件ID'),
            'creater_id' => Yii::t('common', '课表创建者'),
            'start_time' => Yii::t('common', '开始时间'),
            'end_time' => Yii::t('common', '结束时间'),
            'status' => Yii::t('common', ' 正常：10 已结束 ：20 已关闭：30'),
            'created_at' => Yii::t('common', 'Created At'),
            'updeated_at' => Yii::t('common', 'Updeated At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'title' => Yii::t('common', '课程名称'),
            'intro' => Yii::t('common', '课程介绍'),
            'courseware_id' => Yii::t('common', '课件ID'),
            'creater_id' => Yii::t('common', '课表创建者'),
            'start_time' => Yii::t('common', '开始时间'),
            'end_time' => Yii::t('common', '结束时间'),
            'status' => Yii::t('common', ' 正常：10 已结束 ：20 已关闭：30'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\courseQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\courseQuery(get_called_class());
    }


}
