<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "course_category".
 *
 * @property integer $category_id
 * @property integer $parent_id
 * @property string $name
 * @property string $slug
 * @property string $description
 * @property string $banner_src
 * @property integer $creater_id
 * @property integer $status
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class CourseCategory extends \yii\db\ActiveRecord
{
    CONST STATUS_NORMAL = 10;
    CONST STATUS_CLOSED = 20;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course_category';
    }

    /**
     * @inheritdoc
     */
    public static function getDb(){
       return \Yii::$app->get('campus');
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'creater_id', 'status'], 'integer'],
            [['name', 'description', 'banner_src', 'creater_id', 'status'], 'required'],
            [['name', 'slug', 'description', 'banner_src'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'category_id' => '分类ID',
            'parent_id'   => '父分类ID',
            'name'        => '名称',
            'slug'        => 'Slug',
            'description' => '描述',
            'banner_src'  => 'Banner Src',
            'creater_id'  => '创建者ID',
            'updated_at'  => '更新时间',
            'created_at'  => '创建时间',
            'status'      => '状态',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'parent_id' => '选择父分类',
            'slug'      => '如果该字段留空，系统将自动生成一个slug',
            // 'status'    => '正常: 10 ; 关闭：20 ',
        ]);
    }

    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    public static function optsStatus()
    {
        return [
            self::STATUS_NORMAL => Yii::t('azure', '正常'),
            self::STATUS_CLOSED => Yii::t('azure', '关闭'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\CourseCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\CourseCategoryQuery(get_called_class());
    }


}
