<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;

/**
 * This is the base-model class for table "course_schedule".
 *
 * @property integer $course_schedule_id
 * @property integer $course_id
 * @property string $start_time
 * @property string $end_time
 * @property string $which_day
 * @property integer $status
 * @property string $aliasModel
 */
abstract class CourseSchedule extends \yii\db\ActiveRecord
{


    CONST COURSE_STATUS_OPEN   = 10;//正常
    CONST COURSE_STATUS_FINISH = 20; //结束
    CONST COURSE_STATUS_DELECT = 30;//关闭
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course_schedule';
    }
    public static function optsStatus(){
        return [
            self::COURSE_STATUS_OPEN   => '正常',
            self::COURSE_STATUS_FINISH => '结束',
            self::COURSE_STATUS_DELECT => '无效'
        ];
    }

    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['course_id', 'start_time', 'end_time', 'which_day'], 'required'],
            [['course_id', 'teacher_id','status'], 'integer'],
            [['start_time', 'end_time', 'which_day'], 'safe']
        ];
    }

    public static  function getDb(){
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'course_schedule_id' => Yii::t('common', 'Course Schedule ID'),
            'course_id' => Yii::t('common', '课程ID'),
            'start_time' => Yii::t('common', '上课开始时间 '),
            'end_time' => Yii::t('common', '上课结束时间'),
            'which_day' => Yii::t('common', '上课日期'),
            'status' => Yii::t('common', '状态'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'course_id' => Yii::t('common', '课程ID'),
            'start_time' => Yii::t('common', '上课开始时间'),
            'end_time' => Yii::t('common', '上课结束时间'),
            'which_day' => Yii::t('common', '上课日期'),
            'status' => Yii::t('common', '状态'),
        ]);
    }


    public function getCourse(){
        return $this->hasOne(\backend\modules\campus\models\Course::className(),['course_id'=>'course_id']);
    }
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\CourseSchedule the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\CourseSchedule(get_called_class());
    }


}
