<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "couese_order_item".
 *
 * @property integer $couese_order_item_id
 * @property integer $parent_id
 * @property integer $school_id
 * @property integer $grade_id
 * @property integer $user_id
 * @property integer $introducer_id
 * @property integer $payment
 * @property integer $presented_course
 * @property integer $status
 * @property integer $payment_status
 * @property string $total_price
 * @property string $real_price
 * @property string $coupon_price
 * @property integer $total_course
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class CourseOrderItem extends \yii\db\ActiveRecord
{

    const PAYMENT_STATUS_REFUNDED   = 400;     // 400退款
    const PAYMENT_STATUS_PAID       = 300;     // 300已成功支付
    const PAYMENT_STATUS_CONFIRMING = 200;     // 200确认中
    const PAYMENT_STATUS_NON_PAID   = 100;     // 100未支付


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course_order_item';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    public static function getDb(){
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'school_id', 'grade_id', 'user_id', 'introducer_id', 'payment', 'presented_course', 'status', 'payment_status', 'total_course'], 'integer'],
            [['user_id', 'payment', 'payment_status', 'total_price', 'real_price', 'total_course'], 'required'],
            [['total_price', 'real_price', 'coupon_price'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'couese_order_item_id' => Yii::t('backend', 'Couese Order Item ID'),
            'parent_id' => Yii::t('backend', '父订单id'),
            'school_id' => Yii::t('backend', 'School ID'),
            'grade_id' => Yii::t('backend', 'Grade ID'),
            'user_id' => Yii::t('backend', 'User ID'),
            'introducer_id' => Yii::t('backend', '介绍人'),
            'payment' => Yii::t('backend', '100 在线支付； 110 支付宝 支付 ； 111 微信支付；  200 货到付款'),
            'presented_course' => Yii::t('backend', '赠送的课程'),
            'status' => Yii::t('backend', '订单的状态'),
            'payment_status' => Yii::t('backend', '支付状态 100未支付；200 确认中 ； 300 已支付； '),
            'total_price' => Yii::t('backend', '总价'),
            'real_price' => Yii::t('backend', '实际付款'),
            'coupon_price' => Yii::t('backend', '优惠金额'),
            'total_course' => Yii::t('backend', '课程的总数'),
            'created_at' => Yii::t('backend', 'Created At'),
            'updated_at' => Yii::t('backend', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'parent_id' => Yii::t('backend', '父订单id'),
            'introducer_id' => Yii::t('backend', '介绍人'),
            'payment' => Yii::t('backend', '100 在线支付； 110 支付宝 支付 ； 111 微信支付；  200 货到付款'),
            'presented_course' => Yii::t('backend', '赠送的课程'),
            'status' => Yii::t('backend', '订单的状态'),
            'payment_status' => Yii::t('backend', '支付状态 100未支付；200 确认中 ； 300 已支付； '),
            'total_price' => Yii::t('backend', '总价'),
            'real_price' => Yii::t('backend', '实际付款'),
            'coupon_price' => Yii::t('backend', '优惠金额'),
            'total_course' => Yii::t('backend', '课程的总数'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\CourseOrderItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\CourseOrderItemQuery(get_called_class());
    }


}
