<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "courseware_category".
 *
 * @property integer $category_id
 * @property integer $parent_id
 * @property string $name
 * @property string $description
 * @property string $banner_src
 * @property integer $creater_id
 * @property integer $status
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class CoursewareCategory extends \yii\db\ActiveRecord
{
    const CATEGORY_STATUS_OPEN = 10;//开启
    const CATEGORY_STATUS_CLOSE = 20;//关闭

    public static function optsStatus(){
        return [
                self::CATEGORY_STATUS_OPEN =>'开启',
                self::CATEGORY_STATUS_CLOSE =>'关闭'
                ];
    }
    public static function StatusValueLabel($value){
            $label = self::optsStatus();
            if(isset($label[$value])){
                return $label[$value];
            }
            return $value;
    }

    public static function getDb(){
        //return \Yii::$app->getModules('campus')->get('campus');
        //return Yii::$app->modules['campus']->get('campus');
        return Yii::$app->get('campus');
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'courseware_category';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'creater_id', 'status'], 'integer'],
            [['name', 'description', 'banner_src', 'creater_id', 'status'], 'required'],
            [['name'], 'string', 'max' => 225],
            [['slug'], 'string', 'max' => 32],
            [['description', 'banner_src'], 'string', 'max' => 255],
            [['parent_id'], 'default','value' => 0]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'category_id' => Yii::t('backend', 'ID'),
            'parent_id' => Yii::t('backend', '父分类'),
            'name' => Yii::t('backend', '名称'),
            'description' => Yii::t('backend', '描述'),
            'banner_src' => Yii::t('backend', '图片'),
            'creater_id' => Yii::t('backend', '创建者'),
            'updated_at' => Yii::t('backend', '更新时间'),
            'created_at' => Yii::t('backend', '创建时间'),
            'status' => Yii::t('backend', '状态'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'category_id' => Yii::t('backend', 'ID'),
            'parent_id' => Yii::t('backend', '默认顶级分类'),
            'name' => Yii::t('backend', '名称'),
            'description' => Yii::t('backend', '描述'),
            'banner_src' => Yii::t('backend', '图片'),
            'creater_id' => Yii::t('backend', '创建者'),
            'updated_at' => Yii::t('backend', '更新时间'),
            'created_at' => Yii::t('backend', '创建时间'),
            'status' => Yii::t('backend', '正常: 10 ; 关闭：20 '),
        ]);
    }

    public function getUser(){
        return $this->hasOne(\common\models\User::className(),['id'=>'creater_id']);
    }
    
    public function getCourseware(){
        return $this->hasMany(\backend\modules\campus\models\Courseware::className(),['category_id'=>'category_id']);
    }
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\CoursewareCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\CoursewareCategoryQuery(get_called_class());
    }


}
