<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "course_category".
 *
 * @property integer $category_id
 * @property integer $parent_id
 * @property string $name
 * @property string $slug
 * @property string $description
 * @property string $banner_src
 * @property integer $creater_id
 * @property integer $status
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class CourseCategory extends \yii\db\ActiveRecord
{
    CONST STATUS_NORMAL = 10;
    CONST STATUS_CLOSED = 20;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course_category';
    }

    /**
     * @inheritdoc
     */
    public static function getDb(){
       return \Yii::$app->get('campus');
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'creater_id', 'status'], 'integer'],
            [['name', 'description', 'banner_src', 'creater_id', 'status'], 'required'],
            [['name', 'slug', 'description', 'banner_src'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'category_id' => 'Category ID',
            'parent_id' => '父ID',
            'name' => 'Name',
            'slug' => 'Slug',
            'description' => 'Description',
            'banner_src' => 'Banner Src',
            'creater_id' => 'Creater ID',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
            'status' => '状态；正常: 10 ; 关闭：20 ',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'parent_id' => '父ID',
            'status' => '正常: 10 ; 关闭：20 ',
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\CourseCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\CourseCategoryQuery(get_called_class());
    }


}
