<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "feedback".
 *
 * @property string $feedback_id
 * @property integer $feedback_rater
 * @property string $content
 * @property integer $client_source_type
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Feedback extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'feedback';
    }

    /**
     * @inheritdoc
     */
    public static function getDb(){
       return \Yii::$app->get('campus');
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['feedback_rater_id', 'content'], 'required'],
            [['feedback_rater_id', 'client_source_type'], 'integer'],
            [['content'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'feedback_id' => 'Feedback ID',
            'school_id' => 'School ID',
            'feedback_rater_id' => 'Feedback Rater ID',
            'content' => 'Content',
            'client_source_type' => 'Client Source Type',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'school_id' => '学校 ID',
            'feedback_rater_id' => '反馈者ID',
            'content' => '反馈内容',
            'client_source_type' => '10:PC;20:安卓；30：IOS',
        ]);
    }




}
