<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "grade_category".
 *
 * @property integer $grade_category_id
 * @property integer $parent_id
 * @property string  $name
 * @property integer $creater_id
 * @property integer $status
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class GradeCategory extends \yii\db\ActiveRecord
{

    CONST CATEGORY_OPEN     = 10; //正常
    CONST CATEGORY_INVALID  = 20; //无效的


    public static function optsStatus(){
        return [
            self::CATEGORY_OPEN     => '正常',
            self::CATEGORY_INVALID  => '无效'
        ];
    }

    public function getStatusLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    public static function getDb(){
       //return \Yii::$app->modules['campus']->get('campus');
        return Yii::$app->get('campus');
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'grade_category';
    }



    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['creater_id', 'status'], 'integer'],
            ['creater_id','default','value'=>Yii::$app->user->identity->id],
            [['name', 'creater_id', 'status'], 'required'],
            [['name'], 'string', 'max' => 225]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'grade_category_id' => Yii::t('backend', '分类ID'),
            'parent_id'         => Yii::t('backend', '父分类'),
            'name'              => Yii::t('backend', '名称'),
            'creater_id'        => Yii::t('backend', '创建者'),
            'updated_at'        => Yii::t('backend', '更新时间'),
            'created_at'        => Yii::t('backend', '创建时间'),
            'status'            => Yii::t('backend', '状态'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'parent_id' => Yii::t('backend', '父分类'),
            'status'    => Yii::t('backend', '状态'),
        ]);
    }

    public static function getUserName($id)
    {
        $user = \common\models\User::findOne($id);
        $name = '';
        if(isset($user->realname) && !empty($user->realname)){
            return $user->realname;
        }
        if(isset($user->username) && !empty($user->username)){
           return $user->username;
        }
        // if(isset($user->phone_number) && !empty($user->phone_number)){
        //     return $user->phone_number;
        // }
        return $name;
    }
    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\GradeCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\GradeCategoryQuery(get_called_class());
    }


}
