<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "grade".
 *
 * @property integer $grade_id
 * @property integer $school_id
 * @property integer $classroom_group_levels
 * @property string  $grade_name
 * @property integer $grade_title
 * @property integer $owner_id
 * @property integer $creater_id
 * @property integer $sort
 * @property integer $status
 * @property integer $graduate
 * @property integer $time_of_graduation
 * @property integer $time_of_enrollment
 * @property integer $updated_at
 * @property integer $created_at
 *
 * @property \backend\modules\campus\models\GradeProfile $gradeProfile
 * @property string $aliasModel
 */
abstract class Grade extends \yii\db\ActiveRecord
{
    CONST GRADE_STATUS_OPEN = 10;//正常。
    CONST GRANE_STATUS_DELECT = 0;//标记性删除。

    CONST GRANE_GRADUATE = 0;//毕业
    CONST GRADE_NOT_GRADUATE = 1;//未毕业

    public static function optsGraduate(){
        return [
            self::GRADE_NOT_GRADUATE => '未毕业',
            self::GRANE_GRADUATE => '毕业',
        ];
    }

    public static function getGraduateValue($value){
        $label = self::optsGraduate();
        if($label[$value]){
            return $label[$value];
        }
        return $value;
    }

    public static  function optsStatus(){
        return [
            self::GRADE_STATUS_OPEN => '开启',
            self::GRANE_STATUS_DELECT => '删除'
        ];
    }

    public static function getStatusValueLabel($value){
        $label = self::optsStatus();
        if(isset($label[$value])){
            return $label[$value];
        }
        return $value;
    }
     /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return \Yii::$app->modules['campus']->get('campus');
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'grade';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['school_id', 'grade_title','group_category_id'], 'required'],
            ['creater_id','default','value'=>Yii::$app->user->identity->id],
            [['school_id', 'grade_title', 'owner_id', 'creater_id', 'sort', 'status', 'graduate', 'time_of_graduation', 'time_of_enrollment','group_category_id'], 'integer'],
            [['grade_name'], 'string', 'max' => 32]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'grade_id' => Yii::t('common', '班级ID'),
            'school_id' => Yii::t('common', '学校ID'),
            'grade_name' => Yii::t('common', '班级名'),
            'grade_title' => Yii::t('common', '几班'),
            'group_category_id' => Yii::t('common','班级类型'),
            'owner_id' => Yii::t('common', '班主任'),
            'creater_id' => Yii::t('common', '创建者ID'),
            'updated_at' => Yii::t('common', '创建时间戳'),
            'created_at' => Yii::t('common', '创建时间戳'),
            'sort' => Yii::t('common', '默认与排序'),
            'status' => Yii::t('common', '状态:10 正常；0标记删除'),
            'graduate' => Yii::t('common', '0未毕业；1毕业'),
            'time_of_graduation' => Yii::t('common', '毕业时间：年表示第几届'),
            'time_of_enrollment' => Yii::t('common', '入学时间'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'grade_id' => Yii::t('common', '班级ID'),
            'school_id' => Yii::t('common', '学校ID'),
            'group_category_id' => Yii::t('common','班级分类'),
            // 'classroom_group_levels' => Yii::t('common', '班级名称'),
            'grade_name' => Yii::t('common', '班级'),
            'grade_title' => Yii::t('common', '几班'),
            'owner_id' => Yii::t('common', '所属班主任ID'),
            'creater_id' => Yii::t('common', '创建者ID'),
            'updated_at' => Yii::t('common', '创建时间戳'),
            'created_at' => Yii::t('common', '创建时间戳'),
            'sort' => Yii::t('common', '默认与排序'),
            'status' => Yii::t('common', '状态:10 正常；0标记删除'),
            'graduate' => Yii::t('common', '0未毕业；1毕业'),
            'time_of_graduation' => Yii::t('common', '毕业时间：年表示第几届'),
            'time_of_enrollment' => Yii::t('common', '入学时间'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGradeProfile()
    {
        return $this->hasOne(\backend\modules\campus\models\GradeProfile::className(), ['grade_id' => 'grade_id']);
    }
    /**
     * *
     * @return [type] [description]
     */
    public function getSchool(){
        return $this->hasOne(\backend\modules\campus\models\School::className(),['id'=>'school_id']);
    }
    
    public function getGradeCategory(){
        return $this->hasOne(\backend\modules\campus\models\GradeCategory::ClassName(),['grade_category_id'=>'group_category_id']);
    }

    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\GradeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\GradeQuery(get_called_class());
    }

}
