<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use backend\modules\campus\models\CnCity;
use backend\modules\campus\models\CnProvince;
use backend\modules\campus\models\CnRegion;
use yii\helpers\ArrayHelper;
/**
 * This is the base-model class for table "school".
 *
 * @property integer $id
 * @property integer $parent_id
 * @property integer $school_id
 * @property string $language
 * @property string $school_title
 * @property string $school_short_title
 * @property string $school_slogan
 * @property string $school_logo_path
 * @property string $school_backgroud_path
 * @property double $longitude
 * @property double $latitude
 * @property string $address
 * @property integer $province_id
 * @property integer $city_id
 * @property integer $region_id
 * @property integer $created_id
 * @property integer $status
 * @property integer $sort
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class School extends \yii\db\ActiveRecord
{

    CONST SCHOOL_STATUS_OPEN = 0;       //开启;
    CONST SCHOOL_STATUS_DELECT = 1;     //标记删除;
    CONST SCHOOL_STATUS_CHECK_PENDING = 2;//待审核;

    /**
     * @inheritdoc
     */
    public static function optsStatus()
    {
        return [
            self::SCHOOL_STATUS_OPEN => Yii::t('backend','开启'),
            self::SCHOOL_STATUS_DELECT => Yii::t('backend','标记删除'),
           // self::SCHOOL_STATUS_CHECK_PENDIND => Yii::t('backent','待审核')
        ];
    }
    public static function getStatusValueLabel($value)
    {
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }
    public static function tableName()
    {
        return 'school';
    }
    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
     public static function getDb()
     {
        //dump(Yii::$app);
        //dump();exit;
       // dump(\Yii::$app->modules['campus']->get('campus'),Yii::$app->get('db'),Yii::$app->get('campus'));exit;
        //return \Yii::$app->modules['campus']->get('campus');
        return Yii::$app->get('campus');
     }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'school_id', 'province_id', 'city_id', 'region_id', 'created_id', 'status', 'sort'], 'integer'],
            ['parent_id','default','value'=>'0'],
            ['created_id','default','value'=>Yii::$app->user->identity->id],
            [[ 'school_title', 'province_id', 'city_id', 'region_id', 'created_id'], 'required'],
            [['longitude', 'latitude'], 'number'],
            [['language'], 'string', 'max' => 32],
            [['school_title', 'school_slogan'], 'string', 'max' => 512],
            [['school_short_title'], 'string', 'max' => 128],
            [['school_logo_path', 'school_backgroud_path', 'address'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'                    => Yii::t('backend', '自增ID'),
            'parent_id'             => Yii::t('backend', '主校ID'),
            'school_id'             => Yii::t('backend', '学校ID'),
            'language'              => Yii::t('backend', '语言'),
            'school_title'          => Yii::t('backend', '学校名称'),
            'school_short_title'    => Yii::t('backend', '学校简称'),
            'school_slogan'         => Yii::t('backend', '学校标语'),
            'school_logo_path'      => Yii::t('backend', 'Logo路径'),
            'school_backgroud_path' => Yii::t('backend', '学校背景图路径'),
            'longitude'             => Yii::t('backend', '经度'),
            'latitude'              => Yii::t('backend', '纬度'),
            'address'               => Yii::t('backend', '地址'),
            'province_id'           => Yii::t('backend', '省'),
            'city_id'               => Yii::t('backend', '城市'),
            'region_id'             => Yii::t('backend', '区县'),
            'created_at'            => Yii::t('backend', 'Created At'),
            'updated_at'            => Yii::t('backend', 'Updated At'),
            'created_id'            => Yii::t('backend', 'Created ID'),
            'status'                => Yii::t('backend', '状态'),
            'sort'                  => Yii::t('backend', '排序'),
        ];
    }

    public function fields(){
        return ArrayHelper::merge(
            parent::fields(),
            [
            'school_id'=>function(){
                return (int)$this->school_id;
            },
            'parent_id'=>function(){
                return (int)$this->parent_id;
            } ,
            'province_id'=>function(){
                return (int)$this->province_id;
            },
            'city_id'=>function(){
                return (int)$this->city_id;
            },
            'created_id'=>function(){
                return (int)$this->created_id;
            },
            'region_id'=>function(){
                return (int)$this->region_id;
            },
            'status'=>function(){
                return (int)$this->status;
            }
        ]);
    }
    

    
    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id'                    => Yii::t('backend', '自增ID'),
            'parent_id'             => Yii::t('backend', '主校ID'),
            'school_id'             => Yii::t('backend', '学校ID'),
            'language'              => Yii::t('backend', '语言'),
            'school_title'          => Yii::t('backend', '学校名称'),
            'school_short_title'    => Yii::t('backend', '学校简称'),
            'school_slogan'         => Yii::t('backend', '学校标语'),
            'school_logo_path'      => Yii::t('backend', 'Logo路径'),
            'school_backgroud_path' => Yii::t('backend', '学校背景图路径'),
            'longitude'             => Yii::t('backend', '经度'),
            'latitude'              => Yii::t('backend', '纬度'),
            'address'               => Yii::t('backend', '地址'),
            'province_id'           => Yii::t('backend', '省'),
            'city_id'               => Yii::t('backend', '城市'),
            'region_id'             => Yii::t('backend', '区县'),
            'status'                => Yii::t('backend', '状态'),
            'sort'                  => Yii::t('backend', '排序'),
        ]);
    }

    /**
    * 三级联动地区
    **/
    public function getCitylist($typeid = 0,$id = false){
        if($typeid == 1){
            $province = CnProvince::find()->asArray()->all();
            return  ArrayHelper::map($province, 'province_id', 'province_name');
        }
        if($typeid == 2){
            $city    = CnCity::find()->where(['province_id'=>$id])->asArray()->all();
            return  ArrayHelper::map($city, 'city_id', 'city_name');
        }
            $region  = CnRegion::find()->where(['city_id'=>$id])->asArray()->all();
            return  ArrayHelper::map($region, 'region_id', 'region_name');
    }

    public function getCity(){
        return $this->hasOne(\backend\modules\campus\models\CnCity::ClassName(),['city_id'=>'city_id']);
    }
    public function getProvince(){
        return $this->hasOne(\backend\modules\campus\models\CnProvince::ClassName(),['province_id'=>'province_id']);
    }
    public function getRegion(){
        return $this->hasOne(\backend\modules\campus\models\CnRegion::ClassName(),['region_id'=>'region_id']);
    }
    public function getSchool(){
        return $this->hasOne(\backend\modules\campus\models\School::ClassName(),['parent_id'=>'school_id']);
    }
      public function getGrade(){
        return $this->hasOne(\backend\modules\campus\models\Grade::ClassName(),['school_id'=>'school_id']);
    }
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\SchoolQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\SchoolQuery(get_called_class());
    }


}
