<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "share_stream_to_grade".
 *
 * @property integer $share_stream_id
 * @property string $school_id
 * @property string $grade_id
 * @property integer $status
 * @property integer $auditor_id
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class ShareStreamToGrade extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'share_stream_to_grade';
    }
    public static function getDb(){
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['share_stream_id'], 'required'],
            [['status', 'auditor_id'], 'integer'],
            ['status','default','value'=>10],
            [['school_id', 'grade_id'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'share_stream_id' => Yii::t('backend', 'Share Stream ID'),
            'school_id' => Yii::t('backend', 'School ID'),
            'grade_id' => Yii::t('backend', '学校id'),
            'status' => Yii::t('backend', '状态'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'created_at' => Yii::t('backend', 'Created At'),
            'auditor_id' => Yii::t('backend', '审核者'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'grade_id' => Yii::t('backend', '审核人'),
            'status' => Yii::t('backend', '状态'),
            'auditor_id' => Yii::t('backend', '审核者'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\ShareStreamToGradeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\ShareStreamToGradeQuery(get_called_class());
    }


}
