<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "sign_in".
 *
 * @property integer $signin_id
 * @property integer $school_id
 * @property integer $grade_id
 * @property integer $course_id
 * @property integer $student_id
 * @property integer $teacher_id
 * @property integer $auditor_id
 * @property integer $status
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class SignIn extends \yii\db\ActiveRecord
{

    const STATUS_UNREAD = 0;    // 未查看
    const STATUS_READ   = 10;   // 已查看

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sign_in';
    }

    public static function getDb(){
       return \Yii::$app->modules['campus']->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['school_id', 'grade_id', 'course_id', 'student_id', 'teacher_id'], 'required'],
            [['school_id', 'grade_id', 'course_id', 'student_id', 'teacher_id', 'auditor_id', 'status'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'signin_id'  => Yii::t('common', '签到记录ID'),
            'school_id'  => Yii::t('common', '学校ID'),
            'grade_id'   => Yii::t('common', '班级ID'),
            'course_id'  => Yii::t('common', '课程ID'),
            'student_id' => Yii::t('common', '学员ID'),
            'teacher_id' => Yii::t('common', '教师ID'),
            'auditor_id' => Yii::t('common', '审核人'),
            'status'     => Yii::t('common', '状态'),
            'updated_at' => Yii::t('common', '更新时间'),
            'created_at' => Yii::t('common', '签到时间'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'signin_id'  => Yii::t('common', '签到记录ID'),
            'school_id'  => Yii::t('common', '学校ID'),
            'grade_id'   => Yii::t('common', '班级ID'),
            'course_id'  => Yii::t('common', '课程ID'),
            'student_id' => Yii::t('common', '学员ID'),
            'teacher_id' => Yii::t('common', '教师ID'),
            'auditor_id' => Yii::t('common', '审核人'),
            'status'     => Yii::t('common', '状态'),
            'updated_at' => Yii::t('common', '更新时间'),
            'created_at' => Yii::t('common', '签到时间'),
        ]);
    }

    public static function optsSignInStatus()
    {
        return [
            self::STATUS_READ   => Yii::t('common', '已查看'),
            self::STATUS_UNREAD => Yii::t('common', '未查看'),
        ];
    }
    
    public function getSignInStatusLabel($value)
    {
        $labels = self::optsSignInStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    public function getSchool()
    {
        return $this->hasOne(\backend\modules\campus\models\School::className(),['id' => 'school_id']);
    }

    public function getGrade()
    {
        return $this->hasOne(\backend\modules\campus\models\Grade::className(),['grade_id' => 'grade_id']);
    }

    public function getCourse()
    {
        return $this->hasOne(\backend\modules\campus\models\Course::className(),['course_id' => 'course_id']);
    }

    public static function getUserName($id)
    {
        $user = \common\models\User::findOne($id);
        $name = '';
        if(isset($user->realname) && !empty($user->realname)){
            return $user->realname;
        }
        if(isset($user->username) && !empty($user->username)){
           return $user->username;
        }
        // if(isset($user->phone_number) && !empty($user->phone_number)){
        //     return $user->phone_number;
        // }
        return $name;
    }

    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\SignInQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\SignInQuery(get_called_class());
    }


}
