<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "student_record_key".
 *
 * @property integer $student_record_key_id
 * @property integer $school_id
 * @property integer $grade_id
 * @property string $title
 * @property integer $status
 * @property integer $sort
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class StudentRecordKey extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_record_key';
    }

    public static function getDb(){
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['school_id', 'grade_id', 'status', 'sort'], 'integer'],
            [['title'], 'required'],
            [['title'], 'string', 'max' => 512]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'student_record_key_id' => Yii::t('backend', '自增ID'),
            'school_id' => Yii::t('backend', 'School ID'),
            'grade_id' => Yii::t('backend', 'Grade ID'),
            'title' => Yii::t('backend', '标题'),
            'status' => Yii::t('backend', '1：正常；0标记删除；2待审核；'),
            'sort' => Yii::t('backend', '默认与排序'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'created_at' => Yii::t('backend', 'Created At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'student_record_key_id' => Yii::t('backend', '自增ID'),
            'title' => Yii::t('backend', '标题'),
            'status' => Yii::t('backend', '1：正常；0标记删除；2待审核；'),
            'sort' => Yii::t('backend', '默认与排序'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\StudentRecordKeyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\StudentRecordKeyQuery(get_called_class());
    }


}
