<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
//use backend\modules\campus\models\School;
//use backend\modules\campus\models\Grade;


/**
 * This is the base-model class for table "student_record_key".
 *
 * @property integer $student_record_key_id
 * @property integer $school_id
 * @property integer $grade_id
 * @property string $title
 * @property integer $status
 * @property integer $sort
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class StudentRecordKey extends \yii\db\ActiveRecord
{

    const STUDENT_KEY_STATUS_DELECT = 0;
    const STUDENT_KEY_STATUS_OPEN = 1;
    const STUDENT_KEY_STATUS_AUDIT = 2;

    public static function optsStatus(){
        return [
            self::STUDENT_KEY_STATUS_OPEN =>'正常',
            self::STUDENT_KEY_STATUS_DELECT =>'关闭',
            self::STUDENT_KEY_STATUS_AUDIT =>'待审核',
        ];

    }

    public static function getStatusLabel($value)
    {
        $label = self::optsStatus();
        if (isset($label[$value])) {
            return $label[$value];
        }
        return $value;
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_record_key';
    }



    public static function getDb(){
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['school_id', 'grade_id', 'status', 'sort'], 'integer'],
            [['title'], 'required'],
            [['title'], 'string', 'max' => 512],
            [['school_id','grade_id'],'default','value' => 0,'on' => 'score'],
        ];
    }

    public function scenarios(){
        $scenario = parent::scenarios();
        $scenario['score'] = ['school_id','grade_id','title','status'];
        return $scenario;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'student_record_key_id' => Yii::t('backend', '自增ID'),
            'school_id' => Yii::t('backend', '学校 ID'),
            'grade_id' => Yii::t('backend', '班级 ID'),
            'title' => Yii::t('backend', '标题'),
            'status' => Yii::t('backend', '状态'),
            'sort' => Yii::t('backend', '默认与排序'),
            'updated_at' => Yii::t('backend', '更新时间'),
            'created_at' => Yii::t('backend', '创建时间'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'student_record_key_id' => Yii::t('backend', '自增ID'),
            'title' => Yii::t('backend', '标题'),
            'status' => Yii::t('backend', '1：正常；0标记删除；2待审核；'),
            'sort' => Yii::t('backend', '默认与排序'),
        ]);
    }


     public function getlist($type_id = false,$id =false){
        if($type_id == 1){
            $grade = \backend\modules\campus\models\Grade::find()->where(['status'=>Grade::GRADE_STATUS_OPEN, 'school_id'=>$id])->asArray()->all();
            //var_dump($grade);exit;
            return ArrayHelper::map($grade,'grade_id','grade_name');
        }
        $school = \backend\modules\campus\models\School::find()->where(['status'=>School::SCHOOL_STATUS_OPEN])->asArray()->all();
        return ArrayHelper::map($school,'school_id','school_title');
      }

    public function getSchool()
    {
        return $this->hasOne(\backend\modules\campus\models\School::className(),['school_id' => 'school_id']);
    }

    public function getGrade()
    {
        return $this->hasOne(\backend\modules\campus\models\Grade::className(),['grade_id' => 'grade_id']);
    }
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\StudentRecordKeyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\StudentRecordKeyQuery(get_called_class());
    }


}
