<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "student_record_value".
 *
 * @property integer $student_record_value_id
 * @property integer $student_record_key_id
 * @property integer $student_record_id
 * @property string $body
 * @property integer $status
 * @property integer $sort
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class StudentRecordValue extends \yii\db\ActiveRecord
{

    const STUDENT_VALUE_STATUS_OPEN  = 1;//正常
    const STUDENT_VALUE_STATUS_CLOSE = 0;//关闭

    public static function optsStatus(){
        return [
            self::STUDENT_VALUE_STATUS_OPEN  => '正常',
            self::STUDENT_VALUE_STATUS_CLOSE => '关闭',
        ];
    }

    public static function  getStatusValueLabel($value){
        $label = self::optsStatus();
        if(isset($label[$value])){
            return $label[$value];
        }
        return $value;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_record_value';
    }

    public static function getDb(){
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_record_key_id', 'student_record_id'], 'required'],
            [['student_record_key_id', 'student_record_id', 'status', 'sort'], 'integer'],
            [['body'], 'string', 'max' => 1024],
            [['user_id','school_id','grade_id','score','total_score'],'required','on'=>'course'],
        ];
    }

    public function scenarios(){
        $scenario = parent::scenarios();
        $scenario['course'] = ['user_id','grade_id','student_record_id','grade_id','score','total_score','status','sort'];
        return $scenario;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'student_record_value_id' => Yii::t('backend', '自增ID'),
            'student_record_key_id' => Yii::t('backend', '标题ID'),
            'student_record_id' => Yii::t('backend', '学员档案ID'),
            'body' => Yii::t('backend', '学员档案条目描述'),
            'status' => Yii::t('backend', '1：正常；0标记删除；2待审核；'),
            'sort' => Yii::t('backend', '默认与排序'),
            'updated_at' => Yii::t('backend', '更新时间'),
            'created_at' => Yii::t('backend', '创建时间'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'student_record_value_id' => Yii::t('backend', '自增ID'),
            'student_record_key_id' => Yii::t('backend', '标题ID'),
            'student_record_id' => Yii::t('backend', '学员档案ID'),
            'body' => Yii::t('backend', '学员档案条目描述'),
            'status' => Yii::t('backend', '1：正常；0标记删除；2待审核；'),
            'sort' => Yii::t('backend', '默认与排序'),
        ]);
    }

    public function getStudentRecordValueToFile(){
        return $this->hasMany(\backend\modules\campus\models\StudentRecordValueToFile::className(),['student_record_value_id'=>'student_record_value_id']);
    }
    public function getStudentRecordKey(){
        return $this->hasOne(\backend\modules\campus\models\StudentRecordKey::className(),['student_record_key_id'=>'student_record_key_id']);
    }
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\StudentRecordValueQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\StudentRecordValueQuery(get_called_class());
    }


}
