<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;

/**
 * This is the base-model class for table "student_record_value_to_file".
 *
 * @property integer $student_record_value_to_file_id
 * @property integer $student_record_value_id
 * @property integer $file_storage_item_id
 * @property string $aliasModel
 */
abstract class StudentRecordValueToFile extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_record_value_to_file';
    }

    public static function getDb(){
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_record_value_id', 'file_storage_item_id'], 'required'],
            [['student_record_value_id', 'file_storage_item_id'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'student_record_value_to_file_id' => Yii::t('backend', 'Student Record Value To File ID'),
            'student_record_value_id' => Yii::t('backend', 'Student Record Value ID'),
            'file_storage_item_id' => Yii::t('backend', 'File Storage Item ID'),
        ];
    }
    public function getFileStorageItem(){
        return $this->hasOne(
            \backend\modules\campus\models\FileStorageItem::className(),
            ['file_storage_item_id'=>'file_storage_item_id']
        );
    }

    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\StudentRecordValueToFileQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\StudentRecordValueToFileQuery(get_called_class());
    }


}
