<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "users_to_school".
 *
 * @property integer $user_to_school_id
 * @property integer $user_id
 * @property integer $school_id
 * @property integer $user_title_id_at_school
 * @property integer $status
 * @property integer $sort
 * @property integer $school_user_type
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class UserToSchool extends \yii\db\ActiveRecord
{
     /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        //return \Yii::$app->modules['campus']->get('campus');
        return Yii::$app->get('campus');
    }



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users_to_school';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'school_id'], 'required'],
            [['user_id', 'school_id', 'user_title_id_at_school', 'status', 'sort', 'school_user_type'], 'integer'],
            [['user_id', 'school_id'], 'unique', 'targetAttribute' => ['user_id', 'school_id'], 'message' => 'The combination of 用户ID and 学校ID has already been taken.']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_to_school_id' => Yii::t('common', 'User To School ID'),
            'user_id' => Yii::t('common', '用户ID'),
            'school_id' => Yii::t('common', '学校ID'),
            'user_title_id_at_school' => Yii::t('common', '用户在学校的描述性展示Title，没有逻辑'),
            'status' => Yii::t('common', '1：正常；0标记删除；2待审核；3已经转班; '),
            'sort' => Yii::t('common', '显示排序'),
            'school_user_type' => Yii::t('common', '用户关系类型：用户类型：教师；学生；家长；'),
            'updated_at' => Yii::t('common', 'Updated At'),
            'created_at' => Yii::t('common', 'Created At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'user_id' => Yii::t('common', '用户ID'),
            'school_id' => Yii::t('common', '学校ID'),
            'user_title_id_at_school' => Yii::t('common', '用户在学校的描述性展示Title，没有逻辑'),
            'status' => Yii::t('common', '1：正常；0标记删除；2待审核；3已经转班; '),
            'sort' => Yii::t('common', '显示排序'),
            'school_user_type' => Yii::t('common', '用户关系类型：用户类型：教师；学生；家长；'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\UesrToSchool the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\UserToSchool(get_called_class());
    }


}
