<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "users_to_grade".
 *
 * @property integer $user_to_grade_id
 * @property integer $user_id
 * @property integer $school_id
 * @property integer $grade_id
 * @property integer $user_title_id_at_grade
 * @property integer $status
 * @property integer $sort
 * @property integer $grade_user_type
 * @property integer $updated_at
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class UserToGrade extends \yii\db\ActiveRecord
{
    CONST USER_GRADE_STATUS_NORMAL  = 1 ; //正常；
    CONST USER_GRADE_STATUS_RETIRED = 4 ; //退休；
    CONST USER_GRADE_STATUS_CHANGE  = 3 ; //转班；
    CONST USER_GRADE_STATUS_DELETE  = 0 ; // 删除；

    CONST GRADE_USER_TYPE_STUDENT   = 10 ; //学生
    CONST GRADE_USER_TYOE_TEACHER   = 20 ; //老师

    public static function optsStatus(){
        return [
            self::USER_GRADE_STATUS_NORMAL  =>  '正常',
            self::USER_GRADE_STATUS_RETIRED =>  '退休',
            self::USER_GRADE_STATUS_CHANGE  =>  '转班',
            self::USER_GRADE_STATUS_DELETE  =>  '删除',
        ];
    }

    public static function optsUserType(){
        return [
            self::GRADE_USER_TYPE_STUDENT=>'学生',//,
            self::GRADE_USER_TYOE_TEACHER=>'老师',//,
        ];
    }

    public static function UserToTypelable($value){
        $lable = self::optsUserType();
        if(isset($lable[$value])){
            return $lable[$value];
        }
            return $value;
    }

     /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        // dump(\Yii::$app->modules['campus']->get('campus'));exit;
        //return \Yii::$app->getModule('campus')->campus;
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users_to_grade';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'school_id', 'grade_id'], 'required'],
            [['user_id', 'school_id', 'grade_id', 'user_title_id_at_grade', 'status', 'sort', 'grade_user_type'], 'integer'],
            [['user_id', 'school_id', 'grade_id', 'grade_user_type'], 'unique', 'targetAttribute' => ['user_id', 'school_id', 'grade_id', 'grade_user_type'], 'message' => 'The combination of 用户ID, 学校ID, 班级ID and 关系类型: 用户学校关系表类型的子类型 has already been taken.']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_to_grade_id' => Yii::t('common', '学生与班级关系自增ID'),
            'user_id' => Yii::t('common', '用户ID'),
            'school_id' => Yii::t('common', '学校ID'),
            'grade_id' => Yii::t('common', '班级ID'),
            'user_title_id_at_grade' => Yii::t('common', '用户在班级的描述性展示Title，没有逻辑'),
            'status' => Yii::t('common', '1：正常；0标记删除；2待审核；3已经转班; 4已经退休 '),
            'sort' => Yii::t('common', '默认与排序'),
            'grade_user_type' => Yii::t('common', '关系类型: 用户学校关系表类型的子类型'),
            'updated_at' => Yii::t('common', 'Updated At'),
            'created_at' => Yii::t('common', 'Created At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'user_to_grade_id' => Yii::t('common', '学生与班级关系自增ID'),
            'user_id' => Yii::t('common', '用户ID'),
            'school_id' => Yii::t('common', '学校ID'),
            'grade_id' => Yii::t('common', '班级ID'),
            'user_title_id_at_grade' => Yii::t('common', '用户在班级的描述性展示Title，没有逻辑'),
            'status' => Yii::t('common', '1：正常；0标记删除；2待审核；3已经转班; 4已经退休 '),
            'sort' => Yii::t('common', '默认与排序'),
            'grade_user_type' => Yii::t('common', '关系类型: 用户学校关系表类型的子类型'),
        ]);
    }
    public function getGrade(){

        return $this->hasOne(\backend\modules\campus\models\Grade::className(),['grade_id'=>'grade_id']);
    }

    public function getUser(){
        return $this->hasOne(\common\models\User::className(),['id'=>'user_id']);
    }
    public function getSchool(){
        return $this->hasOne(\backend\modules\campus\models\School::className(),['school_id'=>'school_id']);
    }
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\UserToGradeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\UserToGradeQuery(get_called_class());
    }


}
