<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "work_recourd".
 *
 * @property integer $work_record_id
 * @property integer $user_id
 * @property integer $auditer_id
 * @property string $title
 * @property string $body
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class WorkRecord extends \yii\db\ActiveRecord
{

    CONST TYPE_ONE   = 1; //上传学生档案
    CONST TYPE_TWO   = 2; //上正课
    CONST TYPE_THREE = 3; //备课
    CONST TYPE_FOUR  = 4; //家长访问

    CONST STATUS_FULFILL    = 10; //完成
    CONST STATUS_UNFINISHED = 20; //未完成
    CONST STATUS_CLOSE = 30; //关闭
    
    public static function optsStatus(){
        return [
            self::STATUS_FULFILL    =>'完成',
            self::STATUS_UNFINISHED =>'未完成',
            self::STATUS_CLOSE      => '关闭',
        ];
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'work_recourd';
    }
    public static function getDb(){
        return Yii::$app->get('campus');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'title', 'status'], 'required'],
            [['user_id', 'auditer_id', 'course_schedule_id','type','status','school_id','grade_id','course_id'], 'integer'],
            [['title'], 'string', 'max' => 225],
            [['body'], 'string', 'max' => 522]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'work_record_id' => Yii::t('common', 'Work Record ID'),
            'user_id' => Yii::t('common', 'User ID'),
            'auditer_id' => Yii::t('common', '审核人'),
            'title' => Yii::t('common', 'Title'),
            'body' => Yii::t('common', 'Body'),
            'status' => Yii::t('common', '10已完成 ；20未完成 ；30 关闭'),
            'created_at' => Yii::t('common', 'Created At'),
            'updated_at' => Yii::t('common', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'auditer_id' => Yii::t('common', '审核人'),
            'status' => Yii::t('common', '10已完成 ；20未完成 ；30 关闭'),
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \backend\modules\campus\models\query\WorkRecordQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \backend\modules\campus\models\query\WorkRecordQuery(get_called_class());
    }


}
