<?php
/**
 * /Users/bruceniu/Documents/GitHub/yii2-starter-kit/backend/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var common\models\UserToken $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="user-token-form">

    <?php $form = ActiveForm::begin([
		'id' => 'UserToken',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger'
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute user_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'user_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\User::find()->all(), 'id', 'id'),
	[
		'prompt' => Yii::t('backend', 'Select'),
		'disabled' => (isset($relAttributes) && isset($relAttributes['user_id'])),
	]
); ?>

<!-- attribute type -->
			<?php echo $form->field($model, 'type')->textInput(['maxlength' => true]) ?>

<!-- attribute token -->
			<?php echo $form->field($model, 'token')->textInput(['maxlength' => true]) ?>

<!-- attribute expire_at -->
			<?php echo $form->field($model, 'expire_at')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('models', 'UserToken'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Save')),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
