<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\controllers\base;

use backend\modules\campus\models\ApplyToPlay;
use backend\modules\campus\models\search\ApplyToPlaySearch;
use common\components\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* ApplyToPlayController implements the CRUD actions for ApplyToPlay model.
*/
class ApplyToPlayController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;

    /**
    * @inheritdoc
    */
    public function behaviors()
    {
    return [
    'access' => [
    'class' => AccessControl::className(),
    'rules' => [
    [
    'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'roles' => ['CampusApplyToPlayFull'],
                    ],
    [
    'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['CampusApplyToPlayView'],
                    ],
    [
    'allow' => true,
                        'actions' => ['update', 'create', 'delete'],
                        'roles' => ['CampusApplyToPlayEdit'],
                    ],
    
                ],
            ],
    ];
    }

/**
* Lists all ApplyToPlay models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new ApplyToPlaySearch;
    $dataProvider = $searchModel->search($_GET);
    $dataProvider->query->andWhere([
                'school_id'=>$this->schoolIdCurrent
        ]);
    $dataProvider->sort = [
            'defaultOrder'=>[
                'updated_at'=>SORT_DESC
            ]
    ];
    Tabs::clearLocalStorage();

    Url::remember();
    \Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
    'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}
/**
* Displays a single ApplyToPlay model.
* @param integer $apply_to_play_id
*
* @return mixed
*/
public function actionView($apply_to_play_id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($apply_to_play_id),
]);
}

/**
* Creates a new ApplyToPlay model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new ApplyToPlay;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'apply_to_play_id' => $model->apply_to_play_id]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing ApplyToPlay model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $apply_to_play_id
* @return mixed
*/
public function actionUpdate($apply_to_play_id)
{
$model = $this->findModel($apply_to_play_id);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing ApplyToPlay model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $apply_to_play_id
* @return mixed
*/
public function actionDelete($apply_to_play_id)
{
try {
$this->findModel($apply_to_play_id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$apply_to_play_id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the ApplyToPlay model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $apply_to_play_id
* @return ApplyToPlay the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($apply_to_play_id)
{
if (($model = ApplyToPlay::findOne($apply_to_play_id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
