<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\controllers\base;

use Yii;
use backend\modules\campus\models\CourseOrderItem;
use backend\modules\campus\models\search\CourseOrderItemSearch;
use common\components\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* CourseOrderItemController implements the CRUD actions for CourseOrderItem model.
*/
class CourseOrderItemController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;

    /**
    * @inheritdoc
    */
    public function behaviors()
    {
    return [
    'access' => [
    'class' => AccessControl::className(),
    'rules' => [
    [
    'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'roles' => ['CampusCourseOrderItemFull'],
                    ],
    [
    'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['CampusCourseOrderItemView'],
                    ],
    [
    'allow' => true,
                        'actions' => ['update', 'create', 'delete'],
                        'roles' => ['CampusCourseOrderItemEdit'],
                    ],
    
                ],
            ],
    ];
    }

/**
* Lists all CourseOrderItem models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new CourseOrderItemSearch;
    $dataProvider = $searchModel->search($_GET);
    $schools[] =  $this->schoolCurrent;//Yii::$app->user->identity->schoolsInfo;
    //$grades = Yii::$app->user->identity->gradesInfo;
    $schools = ArrayHelper::map($schools,'school_id','school_title');
    //$grades  = ArrayHelper::map($grades,'grade_id','grade_name');
    if (env('THEME') == 'edu') {
        $dataProvider->query->andWhere(
                    [
                     'school_id'=>array_keys($schools)
                    ]
            );
    }
    Tabs::clearLocalStorage();

    Url::remember();
    \Yii::$app->session['__crudReturnUrl'] = null;

    return $this->render('index', [
    'dataProvider' => $dataProvider,
        'searchModel' => $searchModel,
        'schools'     => $schools,
    ]);
}

/**
* Displays a single CourseOrderItem model.
* @param integer $course_order_item_id
*
* @return mixed
*/
public function actionView($course_order_item_id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($course_order_item_id),
]);
}

/**
* Creates a new CourseOrderItem model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
    $model = new CourseOrderItem;
    $schools = Yii::$app->user->identity->schoolsInfo;
    $schools = ArrayHelper::map($schools,'school_id','school_title');
    try {
        if ($model->load($_POST) && $model->save()) {
            return $this->redirect(['view', 'course_order_item_id' => $model->course_order_item_id]);
        } elseif (!\Yii::$app->request->isPost) {
            $model->load($_GET);
        }
    } catch (\Exception $e) {
        
        $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
        $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model,'schools'=>$schools]);
}

/**
* Updates an existing CourseOrderItem model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $course_order_item_id
* @return mixed
*/
public function actionUpdate($course_order_item_id)
{
$model = $this->findModel($course_order_item_id);
$schools = Yii::$app->user->identity->schoolsInfo;
    //$grades = Yii::$app->user->identity->gradesInfo;
$schools = ArrayHelper::map($schools,'school_id','school_title');
if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
'schools'=>$schools
]);
}
}

/**
* Deletes an existing CourseOrderItem model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $course_order_item_id
* @return mixed
*/
public function actionDelete($course_order_item_id)
{
try {
$this->findModel($course_order_item_id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$course_order_item_id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the CourseOrderItem model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $course_order_item_id
* @return CourseOrderItem the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($course_order_item_id)
{
if (($model = CourseOrderItem::findOne($course_order_item_id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
