<?php
/**
 * /Users/bruceniu/Documents/GitHub/yii2-starter-kit/backend/runtime/giiant/358b0e44f1c1670b558e36588c267e47
 *
 * @package default
 */


// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\controllers\base;

use backend\modules\campus\models\CoursewareToFile;
use backend\modules\campus\models\search\CoursewareToFileSearch;
use common\components\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
 * CoursewareToFileController implements the CRUD actions for CoursewareToFile model.
 */
class CoursewareToFileController extends Controller
{


	/**
	 *
	 * @var boolean whether to enable CSRF validation for the actions in this controller.
	 * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
	 */
	public $enableCsrfValidation = false;

	/**
	 *
	 * @inheritdoc
	 * @return unknown
	 */
	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'actions' => ['index', 'view', 'create', 'update', 'delete'],
						'roles' => ['CampusCoursewareToFileFull'],
					],
					[
						'allow' => true,
						'actions' => ['index', 'view'],
						'roles' => ['CampusCoursewareToFileView'],
					],
					[
						'allow' => true,
						'actions' => ['update', 'create', 'delete'],
						'roles' => ['CampusCoursewareToFileEdit'],
					],

				],
			],
		];
	}


	/**
	 * Lists all CoursewareToFile models.
	 *
	 * @return mixed
	 */
	public function actionIndex() {
		$searchModel  = new CoursewareToFileSearch;
		$dataProvider = $searchModel->search($_GET);

		Tabs::clearLocalStorage();

		Url::remember();
		\Yii::$app->session['__crudReturnUrl'] = null;

		return $this->render('index', [
				'dataProvider' => $dataProvider,
				'searchModel' => $searchModel,
			]);
	}


	/**
	 * Displays a single CoursewareToFile model.
	 *
	 * @param integer $courseware_to_file_id
	 * @return mixed
	 */
	public function actionView($courseware_to_file_id) {
		\Yii::$app->session['__crudReturnUrl'] = Url::previous();
		Url::remember();
		Tabs::rememberActiveState();

		return $this->render('view', [
				'model' => $this->findModel($courseware_to_file_id),
			]);
	}


	/**
	 * Creates a new CoursewareToFile model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 *
	 * @return mixed
	 */
	public function actionCreate() {
		$model = new CoursewareToFile;

		try {
			if ($model->load($_POST) && $model->save()) {
				return $this->redirect(['view', 'courseware_to_file_id' => $model->courseware_to_file_id]);
			} elseif (!\Yii::$app->request->isPost) {
				$model->load($_GET);
			}
		} catch (\Exception $e) {
			$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
			$model->addError('_exception', $msg);
		}
		return $this->render('create', ['model' => $model]);
	}


	/**
	 * Updates an existing CoursewareToFile model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $courseware_to_file_id
	 * @return mixed
	 */
	public function actionUpdate($id) {
		$model = $this->findModel($id);

		if ($model->load($_POST) && $model->save()) {
			return $this->redirect(Url::previous());
		} else {
			return $this->render('update', [
					'model' => $model,
				]);
		}
	}


	/**
	 * Deletes an existing CoursewareToFile model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $courseware_to_file_id
	 * @return mixed
	 */
	public function actionDelete($id) {
		try {
			$this->findModel($id)->delete();
		} catch (\Exception $e) {
			$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
			\Yii::$app->getSession()->addFlash('error', $msg);
			return $this->redirect(Url::previous());
		}


		// TODO: improve detection
		$isPivot = strstr('$courseware_to_file_id', ',');
		if ($isPivot == true) {
			return $this->redirect(Url::previous());
		} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
			Url::remember(null);
			$url = \Yii::$app->session['__crudReturnUrl'];
			\Yii::$app->session['__crudReturnUrl'] = null;

			return $this->redirect($url);
		} else {
			return $this->redirect(['index']);
		}
	}


	/**
	 * Finds the CoursewareToFile model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 *
	 * @throws HttpException if the model cannot be found
	 * @param integer $courseware_to_file_id
	 * @return CoursewareToFile the loaded model
	 */
	protected function findModel($courseware_to_file_id) {
		if (($model = CoursewareToFile::findOne($courseware_to_file_id)) !== null) {
			return $model;
		} else {
			throw new HttpException(404, 'The requested page does not exist.');
		}
	}


}
