<?php
    // This class was automatically generated by a giiant build task
    // You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\controllers\base;

    use backend\modules\campus\models\School;
    use backend\modules\campus\models\search\SchoolSearch;
    use yii\web\Controller;
    use yii\web\HttpException;
    use yii\helpers\Url;
    use yii\filters\AccessControl;
    use dmstr\bootstrap\Tabs;

    /**
    * SchoolController implements the CRUD actions for School model.
    */
    class SchoolController extends Controller
    {
        /**
        * @var boolean whether to enable CSRF validation for the actions in this controller.
        * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
        */
        public $enableCsrfValidation = false;

            /**
            * @inheritdoc
            */
            public function behaviors()
            {
                return [
                    'access' => [
                        'class' => AccessControl::className(),
                        'rules' => [
                            [
                                'allow' => true,
                                'actions' => ['index', 'view', 'create', 'update', 'delete'],
                                'roles' => ['CampusSchoolFull'],
                            ],
                            [
                                'allow' => true,
                                'actions' => ['index', 'view'],
                                'roles' => ['CampusSchoolView'],
                            ],
                            [
                                'allow' => true,
                                'actions' => ['update', 'create', 'delete'],
                                'roles' => ['CampusSchoolEdit'],
                            ],
                        ],
                    ],
                ];
            }

        /**
        * Lists all School models.
        * @return mixed
        */
        public function actionIndex()
        {
            $searchModel  = new SchoolSearch;
            $dataProvider = $searchModel->search($_GET);

            Tabs::clearLocalStorage();

            Url::remember();
            \Yii::$app->session['__crudReturnUrl'] = null;

            return $this->render('index', [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
            ]);
        }

        /**
        * Displays a single School model.
        * @param integer $id
        *
        * @return mixed
        */
        public function actionView($id)
        {
            \Yii::$app->session['__crudReturnUrl'] = Url::previous();
            Url::remember();
            Tabs::rememberActiveState();

            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }

        /**
        * Creates a new School model.
        * If creation is successful, the browser will be redirected to the 'view' page.
        * @return mixed
        */
        public function actionCreate()
        {
            $model = new School;

            try {
                if ($model->load($_POST) && $model->save()) {
                    $model->school_id = $model->id;
                    $model->save();
                    return $this->redirect(['view', 'id' => $model->id]);
                
                } elseif (!\Yii::$app->request->isPost) {
                    
                    $model->load($_GET);
                
                }
            
            } catch (\Exception $e) {
                $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
                $model->addError('_exception', $msg);
            }
            return $this->render('create', ['model' => $model]);
        }

        /**
        * Updates an existing School model.
        * If update is successful, the browser will be redirected to the 'view' page.
        * @param integer $id
        * @return mixed
        */
        public function actionUpdate($id)
        {
            $model = $this->findModel($id);

            if ($model->load($_POST) && $model->save()) {
            
                return $this->redirect(Url::previous());
           
            } else {
                return $this->render('update', [
                        'model' => $model,
                    ]);
            }
        }

        /**
        * Deletes an existing School model.
        * If deletion is successful, the browser will be redirected to the 'index' page.
        * @param integer $id
        * @return mixed
        */
        public function actionDelete($id)
        {
            try {
                $this->findModel($id)->delete();
            
            } catch (\Exception $e) {
                
                $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
                \Yii::$app->getSession()->addFlash('error', $msg);
                
                return $this->redirect(Url::previous());
        }

            // TODO: improve detection
            $isPivot = strstr('$id',',');
            if ($isPivot == true) {
                return $this->redirect(Url::previous());
           
            } elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
                Url::remember(null);
                $url = \Yii::$app->session['__crudReturnUrl'];
                \Yii::$app->session['__crudReturnUrl'] = null;
                return $this->redirect($url);
            } else {

                return $this->redirect(['index']);

            }
        }

        /**
        * Finds the School model based on its primary key value.
        * If the model is not found, a 404 HTTP exception will be thrown.
        * @param integer $id
        * @return School the loaded model
        * @throws HttpException if the model cannot be found
        */
        protected function findModel($id)
        {
            if (($model = School::findOne($id)) !== null) {
                
                return $model;
            
            } else {
                
                throw new HttpException(404, 'The requested page does not exist.');
            
            }
        }
    }
