<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\controllers\base;

use backend\modules\campus\models\ShareStream;
use backend\modules\campus\models\ShareStreamToGrade;
use backend\modules\campus\models\ShareStreamSearch;
use common\components\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;


/**
* ShareStreamController implements the CRUD actions for ShareStream model.
*/
class ShareStreamController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;

    /**
    * @inheritdoc
    */
    public function behaviors()
    {
    return [
    'access' => [
    'class' => AccessControl::className(),
    'rules' => [
    [
    'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'roles' => ['CampusShareStreamFull'],
                    ],
    [
    'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['CampusShareStreamView'],
                    ],
    [
    'allow' => true,
                        'actions' => ['update', 'create', 'delete'],
                        'roles' => ['CampusShareStreamEdit'],
                    ],
    
                ],
            ],
    ];
    }

/**
* Lists all ShareStream models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new ShareStreamSearch;
    $dataProvider = $searchModel->search($_GET);
    $schoolIds = \Yii::$app->user->identity->schoolsInfo;
    $schoolIds = ArrayHelper::map($schoolIds,'school_id','school_id');
   // var_dump();exit;
    $dataProvider->query->andWhere([
      //  'school_id'=>$schoolIds,
        //'t.grade_id' =>$this->gradeIdCurrent
    ]);
    $dataProvider->sort = [
            'defaultOrder'=>[
                'updated_at'=>SORT_DESC
            ]
    ];
    Tabs::clearLocalStorage();

    Url::remember();
    \Yii::$app->session['__crudReturnUrl'] = null;

    return $this->render('index', [
    'dataProvider' => $dataProvider,
        'searchModel' => $searchModel,
    ]);
}

/**
* Displays a single ShareStream model.
* @param integer $share_stream_id
*
* @return mixed
*/
public function actionView($share_stream_id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($share_stream_id),
]);
}

/**
* Creates a new ShareStream model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new ShareStream;
$shareToGrade = new ShareStreamToGrade;
try {
    if ($model->load($_POST) && $model->save()) {
        return $this->redirect(['view', 'share_stream_id' => $model->share_stream_id]);
    } elseif (!\Yii::$app->request->isPost) {
        $model->load($_GET);
    }
    } catch (\Exception $e) {
        $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
        $model->addError('_exception', $msg);
    }
return $this->render('create', ['model' => $model,'shareToGrade'=>$shareToGrade]);
}

/**
* Updates an existing ShareStream model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $share_stream_id
* @return mixed
*/
public function actionUpdate($share_stream_id)
{
$model = $this->findModel($share_stream_id);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing ShareStream model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $share_stream_id
* @return mixed
*/
public function actionDelete($share_stream_id)
{
try {
$this->findModel($share_stream_id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$share_stream_id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the ShareStream model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $share_stream_id
* @return ShareStream the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($share_stream_id)
{
if (($model = ShareStream::findOne($share_stream_id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
