<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\controllers\base;

use backend\modules\campus\models\SignIn;
use backend\modules\campus\models\search\SignInSearch;
use common\components\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* SignInController implements the CRUD actions for SignIn model.
*/
class SignInController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all SignIn models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new SignInSearch;
    $dataProvider = $searchModel->search($_GET);
    $dataProvider->query->andWhere([
            'sign_in.school_id' => $this->schoolIdCurrent,
            'sign_in.grade_id'  => $this->gradeIdCurrent
        ]);
    $dataProvider->sort = [
        'defaultOrder'=>[
            'updated_at' => SORT_DESC
        ]
    ];

    Tabs::clearLocalStorage();

    Url::remember();
    \Yii::$app->session['__crudReturnUrl'] = null;

    return $this->render('index', [
    'dataProvider' => $dataProvider,
        'searchModel' => $searchModel,
    ]);
}

/**
* Displays a single SignIn model.
* @param integer $signin_id
*
* @return mixed
*/
public function actionView($signin_id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($signin_id),
]);
}

/**
* Creates a new SignIn model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new SignIn;
// var_dump($_POST);exit;
// var_dump($model->load($_POST),$model->save());exit;
try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'signin_id' => $model->signin_id]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing SignIn model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $signin_id
* @return mixed
*/
public function actionUpdate($signin_id)
{
$model = $this->findModel($signin_id);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing SignIn model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $signin_id
* @return mixed
*/
public function actionDelete($signin_id)
{
try {
$this->findModel($signin_id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$signin_id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the SignIn model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $signin_id
* @return SignIn the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($signin_id)
{
if (($model = SignIn::findOne($signin_id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
