<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\modules\campus\controllers\base;
use Yii;
use backend\modules\campus\models\WorkRecord;
    use backend\modules\campus\models\search\WorkRecordSearch;
//use yii\web\Controller;/**/
use common\components\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;
use yii\helpers\ArrayHelper;

/**
* WorkRecordController implements the CRUD actions for WorkRecord model.
*/
class WorkRecordController extends Controller
{
/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;

    /**
    * @inheritdoc
    */
    public function behaviors()
    {
    return [
    'access' => [
    'class' => AccessControl::className(),
    'rules' => [
    [
    'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'roles' => ['CampusWorkRecordFull'],
                    ],
    [
    'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['CampusWorkRecordView'],
                    ],
    [
    'allow' => true,
                        'actions' => ['update', 'create', 'delete'],
                        'roles' => ['CampusWorkRecordEdit'],
                    ],
    
                ],
            ],
    ];
    }

/**
* Lists all WorkRecord models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new WorkRecordSearch;
    $dataProvider = $searchModel->search($_GET);
    $schools[] = $this->schoolCurrent; //Yii::$app->user->identity->schoolsInfo;
    $grades[] =  $this->gradeCurrent;//Yii::$app->user->identity->gradesInfo;
    $schools = ArrayHelper::map($schools,'school_id','school_title');
    $grades  = ArrayHelper::map($grades,'grade_id','grade_name');
// var_dump(array_keys($grades));exit;
    $dataProvider->query->andWhere([
            'school_id'=>array_keys($schools),
            'grade_id' =>array_keys($grades)
    ]);

    if(Yii::$app->user->can('P_director') || Yii::$app->user->can('manager') || Yii::$app->user->can('E_manager')){
    }else{
        $dataProvider->query->andWhere([
            'user_id'=>Yii::$app->user->identity->id,
        ]);
    }
     $dataProvider->sort = [
       'defaultOrder'=>[
            'updated_at'=>SORT_DESC,
       ]
    ];
    Tabs::clearLocalStorage();

    Url::remember();
    \Yii::$app->session['__crudReturnUrl'] = null;
// var_dump('<pre>',$dataProvider);exit;
    return $this->render('index', [
        'dataProvider' => $dataProvider,
        'searchModel' => $searchModel,
        'grades'     =>  $grades,
        'schools'    =>  $schools
    ]);
}

/**
* Displays a single WorkRecord model.
* @param integer $work_record_id
*
* @return mixed
*/
public function actionView($work_record_id)
{
    \Yii::$app->session['__crudReturnUrl'] = Url::previous();
    Url::remember();
    Tabs::rememberActiveState();

    return $this->render('view', [
    'model' => $this->findModel($work_record_id),
    ]);
}

/**
* Creates a new WorkRecord model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
    $model = new WorkRecord;

    try {
        if ($model->load($_POST) && $model->save()) {

            return $this->redirect(['view', 'work_record_id' => $model->work_record_id]);

        } elseif (!\Yii::$app->request->isPost) {
        $model->load($_GET);
    }
    } catch (\Exception $e) {

        $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
        $model->addError('_exception', $msg);
    }
    return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing WorkRecord model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $work_record_id
* @return mixed
*/
public function actionUpdate($work_record_id)
{
$model = $this->findModel($work_record_id);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing WorkRecord model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $work_record_id
* @return mixed
*/
public function actionDelete($work_record_id)
{
try {
$this->findModel($work_record_id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$work_record_id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the WorkRecord model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $work_record_id
* @return WorkRecord the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($work_record_id)
{
if (($model = WorkRecord::findOne($work_record_id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
